### ISSUE TITLE
LearningObjectGoal's source property circular

### ISSUE THREAD

**Issue by gshaw1997** [Cyber4All/database-interaction#12]
@ksherb1 
LearningObjectGoal's source property is circular and causing a Type error when converting to JSON to be sent to client.

Example
```
LearningObject {
  _author:
   User {
     _id: 'gshaw1997',
     _name: 'Gustavus Shaw',
     _email: 'gshaw1997@gmail.com',
     _pwd: null,
     _objects: [] },
  _name: 'My First LO',
  _date: '1513267795449',
  _length: 'unit',
  _goals: [ LearningGoal { _source: [Circular], _text: 'Goal 1' } ],
  _outcomes: [],
  _repository: { files: [], urls: [], notes: '' } }
```

Error: TypeError: Converting circular structure to JSON

**Comment by ksherb1** [comment]
I _think_ this resolved by using the Enitity.serialize and unserialize functions before and after every network transmission, not just those with the db-interactor service. I have updated the readme in the entity repo to explicitly note that.
