### ISSUE TITLE
Ability to check if email is associated with active account

### ISSUE THREAD

**Issue by gshaw1997** [Cyber4All/database-interaction#13]
Need a route similar to /findUser that looks up a user by their email. 

Needed for registration to prevent the reuse of emails associated with active accounts.
https://github.com/Cyber4All/bloomin-onion-client/issues/7

Will provide email string as request param, only need a boolean response indicating whether or not email is attached to an active account.

**Comment by ksherb1** [comment]
This shouldn't be hard; I should have it by Friday.
