### ISSUE TITLE
Complete SuggestObjects function for LearningObject suggestion

### ISSUE THREAD

**Issue by gshaw1997** [Cyber4All/database-interaction#16]
Expressive MongoDB querying possible? If so, need the ability to query the database for LearningObjects by name, source, academic assignments (ie. K-12), and possibly content.

**Comment by ksherb1** [comment]
It is certainly possible. Questions, presumably for our clients:

Regarding the source: do we mean the author? LearningObjects are not in general (by our previous arbitrary definitions) tied to official 'sources' like the outcomes are (though for some of those 'sources' there is an analogy to be drawn, ex. CAE Knowledge Units). But if the goal is to simply search by author's name, that should be easy. If the goal is to search by author's name or username or email, etc., that's more complicated so let me know if that's the goal.

Regarding academic assignment: presently the learning-object entity hasn't got any such field, but it's easy to add. Will it be any arbitrary string? Should it be one of several specific values (ex. 'K-5', '6-8', '9-12', 'College', 'Tech')? Should it, perhaps, be a _list_ of those above specific values, if more than one applies? :/

Regarding content: any ideas how this might look if/when we decide to implement it? I presume it'll basically just be a bit of text we should try to match to each objects' outcomes?

Finally, may I presume that the 'length' (ie. module, nanomodule, course, etc.) should also be included in this list?

**Comment by gshaw1997** [comment]
I'm not 100% sure what source is defined to be, but we should have the ability to search for learning objects by the author. We should only need the ability to search by an author's name, I don't currently see a use case to search by username/email.

Academic assignment as it presently stands has no metadata associated and I believe won't for some time, but they should be represented in a similar fashion to taxonomy levels, verbs etc. 
If more than one assignment applies and is not just a continuation of another assignment (ie. 6-8, 8-12), then yes it should be represented in a _list_ of the specific values.

**Comment by ksherb1** [comment]
The last commit finishes a prototype, documented in the lo-suggestion readme. Behavior is no doubt too strict for the desired use case, but the interface is in place.

**Comment by ksherb1** [comment]
See TODO's in `mongo.driver`'s `suggestObjects` function for thoughts on improving behavior.
