### ISSUE TITLE
Prevent submission when editing learning object name to illegal value

### ISSUE THREAD

**Issue by KolbeML** [Cyber4All/database-interaction#17]
If a user attempts to edit the name of a learning object to become identical to that of an already existing learning object, the changes appear to go through but aren't actually saved. If possible, we should prevent the 'save' button from returning users to the dashboard, and present an appropriate error message.

**Comment by gshaw1997** [comment]
Database Interaction was returning the correct error. Fixed in learning-object-submission.
https://github.com/Cyber4All/learning-object-submission/commit/236ce8b3ccb6f13d387dbb713f2608412403fc02
