### ISSUE TITLE
Access-Control-Allow-Origin for LO-Suggestion

### ISSUE THREAD

**Issue by DonSeannelly** [Cyber4All/database-interaction#18]
### Reasoning
In the current setup of the platform, the learning object suggestion service is directly connected to by both our client applications. Now that we are using HTTP, the browser refuses the connection because there is no ACAO header present on the resource.

It is possible to use a proxy to get around this, but that seems unneeded.

### Request
I suggest that we add the header to the resources.

**Comment by gshaw1997** [comment]
Fixed in commit 
https://github.com/Cyber4All/database-interaction/commit/32e6712fab2175c909e1afb8454147431fa7f75d
