### ISSUE TITLE
Finish user schema

### ISSUE THREAD

**Issue by ksherb1** [Cyber4All/database-interaction#2]
Users need a password and email. This needs to be added to schema, with appropriate adjustments to gluer and driver.

**Comment by ksherb1** [comment]
@DonSeannelly Similar question to the authentication one. Should the database or its interaction layer be responsible for encrypting passwords? It seems to me we shouldn't propagate passwords any more than necessary, so should the gateway API's perform that encryption?

I can also see the argument where asking the db interaction layer to do it is good 'cause then you only have to do it once. What do you think?

**Comment by DonSeannelly** [comment]
I don't have a ton of expertise here, as I usually use third-party services to handle all of this for me. If mongo has an encryption function similar to BASE64 in MySQL, then I would think that would be good enough as that is what onion used when Leon set it up. Otherwise, if Mongo doesn't have an encryption function like that, I would assume we would write a module to do just that before we attempt to store the data.

**Comment by ksherb1** [comment]
Mongo provides encryption at-rest, but from what I can tell it only does so for its Enterprise edition.

Incidentally, "Mongo Atlas", a service where _they_ host our database (providing all maintenance and security [so they claim]), may be worth looking into. I don't really expect it's worthwhile, since I think it's actually just using _their_ AWS EC2 instances rather than our own, and presumably they make a profit. But it may be worth looking into.

**Comment by ksherb1** [comment]
In the meantime, I'll integrate a password hash into my core insert/update/edit functions. There'll be a new @private decorator for entity properties.

As I understand, we store the password hash, and verify the correct password by hashing that and comparing the two. That may warrant a socket.io event (ie. "authenticate", which takes username and password arguments, and returns a boolean indicating the pair is in the database), so that the gateway API's need not concern themselves with the hashing algorithm. Let me know what you think.

**Comment by ksherb1** [comment]
I decided the db user schema should simply be pwdhash, while the user entity has pwd. No @private decorator necessary, since pwdhash is not especially secret. Since going from pwd to hash is a matter of going from entity to schema, that is my db.gluer module's responsibility. I'm using the bcrypt package, which seems to be the node standard for today.
