### ISSUE TITLE
Authenticate database changes

### ISSUE THREAD

**Issue by ksherb1** [Cyber4All/database-interaction#3]
Adapt code from learning-object-submission to ensure changes to an object are only made by users with the appropriate submissions. Will require some change to the interface.

**Comment by ksherb1** [comment]
I've finally pored through learning-object-submission, how its interface interacts with JSON Web Tokens and the database, and I've determined that I don't need to authenticate in this service after all. If the client apps communicate indirectly through other services like learning-object-submission, which handle authentication, and a firewall guarantees that only those services in our cluster communicate with this service, then we're good.

This assumes that (1) all our client apps will have an API service gateway-ing into our cluster, (2) all those gateway services implement appropriate authentication, and (3) we trust our firewall. I don't know much about network security but it seems to me the firewall is always the first to go in the movies. ^_^

(1) and (2) are architecture decisions, so...are those assumptions valid? @DonSeannelly 

If (3) is invalid, then this service will need to require basic admin authentication, which each API service will need to provide, but that need not have anything to do the socket.io event interface.

**Comment by DonSeannelly** [comment]
(1) and (2) are correct. learning-object-submission handles this for neutrino and onion, and cube will get it's own API.

**Comment by ksherb1** [comment]
I will implement authentication to safeguard against firewall penetration soon, but I do not consider that a priority for this milestone.

**Comment by ksherb1** [comment]
After further research, I don't think we'll be able to do any better than the security groups AWS provides, so there's no real reason to bother with additional authentication. (Correct me if I'm wrong.)
